require("plugins-setup")
require("core.options")
require("core.keymaps")
require("plugins.comment")
require("plugins.nvim-tree")
-- require("plugins.lualine")
require("plugins.telescope")
require("plugins.nvim-cmp")
require("plugins.lsp.mason")
require("plugins.lsp.lspsaga")
require("plugins.lsp.lspconfig")
require("plugins.lsp.null-ls")
require("plugins.autopairs")
require("plugins.treesitter")
require("plugins.gitsigns")
-- require("plugins.cmp-emoji")
require("plugins.hop")
require("plugins.bufferline")
require("plugins.rest-nvim")
require("plugins.whichkey")
require("plugins.varios")
require("plugins.dbui")
require("plugins.neodev")
require("plugins.fidget")
-- require("core.colorscheme") --gruvbox-material
require("core.colorscheme-alt") --nightfox-nordfox
require("plugins.mind") --Mind
require("plugins.dressing") --Mind
